/* tslint:disable */
/* eslint-disable */
/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CheckoutInit200Response } from '../models';
// @ts-ignore
import { CheckoutInitDefaultResponse } from '../models';
// @ts-ignore
import { HelcimPayInitializeRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * HelcimPayApi - axios parameter creator
 * @export
 */
export const HelcimPayApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a HelcimPay.js Checkout Session
         * @param {HelcimPayInitializeRequest} [helcimPayInitializeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCheckoutSession: async (helcimPayInitializeRequest?: HelcimPayInitializeRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/helcim-pay/initialize`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiAccessAuth required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "api-token", keyParamName: "apiAccessAuth", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: helcimPayInitializeRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/helcim-pay/initialize',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(helcimPayInitializeRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HelcimPayApi - functional programming interface
 * @export
 */
export const HelcimPayApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HelcimPayApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Creates a HelcimPay.js Checkout Session
         * @param {HelcimPayApiCreateCheckoutSessionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCheckoutSession(requestParameters: HelcimPayApiCreateCheckoutSessionRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckoutInit200Response>> {
            const helcimPayInitializeRequest: HelcimPayInitializeRequest = {
                paymentType: requestParameters.paymentType,
                amount: requestParameters.amount,
                currency: requestParameters.currency,
                customerCode: requestParameters.customerCode,
                invoiceNumber: requestParameters.invoiceNumber,
                paymentMethod: requestParameters.paymentMethod,
                allowPartial: requestParameters.allowPartial,
                hasConvenienceFee: requestParameters.hasConvenienceFee,
                taxAmount: requestParameters.taxAmount
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCheckoutSession(helcimPayInitializeRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * HelcimPayApi - factory interface
 * @export
 */
export const HelcimPayApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HelcimPayApiFp(configuration)
    return {
        /**
         * 
         * @summary Creates a HelcimPay.js Checkout Session
         * @param {HelcimPayApiCreateCheckoutSessionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCheckoutSession(requestParameters: HelcimPayApiCreateCheckoutSessionRequest, options?: AxiosRequestConfig): AxiosPromise<CheckoutInit200Response> {
            return localVarFp.createCheckoutSession(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createCheckoutSession operation in HelcimPayApi.
 * @export
 * @interface HelcimPayApiCreateCheckoutSessionRequest
 */
export type HelcimPayApiCreateCheckoutSessionRequest = {
    
} & HelcimPayInitializeRequest

/**
 * HelcimPayApiGenerated - object-oriented interface
 * @export
 * @class HelcimPayApiGenerated
 * @extends {BaseAPI}
 */
export class HelcimPayApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Creates a HelcimPay.js Checkout Session
     * @param {HelcimPayApiCreateCheckoutSessionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HelcimPayApiGenerated
     */
    public createCheckoutSession(requestParameters: HelcimPayApiCreateCheckoutSessionRequest, options?: AxiosRequestConfig) {
        return HelcimPayApiFp(this.configuration).createCheckoutSession(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
