/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * Contact Name or Business Name
     * @type {string}
     * @memberof Address
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'street1': string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'street2'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'city'?: string;
    /**
     * 2 letter abbreviation of the province(AB, BC, CA). Required field if country is CAN or USA.
     * @type {string}
     * @memberof Address
     */
    'province'?: string;
    /**
     * 3-letter abbreviation of the country(CAN, USA)
     * @type {string}
     * @memberof Address
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'postalCode': string;
    /**
     * 10 to 15 digits phone number.
     * @type {string}
     * @memberof Address
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'email'?: string;
}

