/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BankDataBankData } from './bank-data-bank-data';

/**
 * 
 * @export
 * @interface BankData
 */
export interface BankData {
    /**
     * 
     * @type {BankDataBankData}
     * @memberof BankData
     */
    'bankData': BankDataBankData;
}

