/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BankToken
 */
export interface BankToken {
    /**
     * The token for the bank account on file.
     * @type {string}
     * @memberof BankToken
     */
    'bankToken': string;
}

