/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BankAccount
 */
export interface BankAccount {
    /**
     * The bank account holder first name
     * @type {string}
     * @memberof BankAccount
     */
    'firstName': string;
    /**
     * The bank account holder last name
     * @type {string}
     * @memberof BankAccount
     */
    'lastName': string;
    /**
     * The company name
     * @type {string}
     * @memberof BankAccount
     */
    'companyName': string;
    /**
     * Bank account number
     * @type {string}
     * @memberof BankAccount
     */
    'bankAccountNumber': string;
    /**
     * CHECKING - Chequing, SAVINGS - Savings
     * @type {string}
     * @memberof BankAccount
     */
    'accountType': string;
    /**
     * PERSONAL - Personal Bank Account, CORPORATE - Corporate Bank Account
     * @type {string}
     * @memberof BankAccount
     */
    'accountCorporate': string;
    /**
     * Required for Canadian Bank Account Holder, the institution number - three digits - identifies your bank.
     * @type {string}
     * @memberof BankAccount
     */
    'bankIdNumber'?: string;
    /**
     * Required for Canadian Bank Account Holder, the transit number - five digits - shows which branch you opened your account at.
     * @type {string}
     * @memberof BankAccount
     */
    'transitNumber'?: string;
    /**
     * Required for US Bank Account Holder, a nine-digit code printed on the bottom of checks to identify the financial institution on which it was drawn.
     * @type {string}
     * @memberof BankAccount
     */
    'routingNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    'streetAddress': string;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    'city': string;
    /**
     * Only allow CAN - Canada, USA - United States
     * @type {string}
     * @memberof BankAccount
     */
    'country': string;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    'province': string;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    'postalCode': string;
    /**
     * Customer given permission for a company or financial institution to debit a bank account when the payment is due.
     * @type {boolean}
     * @memberof BankAccount
     */
    'padAgreement'?: boolean;
}

