/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';

/**
 * 
 * @export
 * @interface BankAccountResponse
 */
export interface BankAccountResponse {
    /**
     * The id of the bank account.
     * @type {number}
     * @memberof BankAccountResponse
     */
    'id'?: number;
    /**
     * The id of the customer owning the bank account.
     * @type {number}
     * @memberof BankAccountResponse
     */
    'customerId'?: number;
    /**
     * The date when the bank account is created.
     * @type {string}
     * @memberof BankAccountResponse
     */
    'dateCreated'?: string;
    /**
     * The date when the bank account last got updated.
     * @type {string}
     * @memberof BankAccountResponse
     */
    'dateUpdated'?: string;
    /**
     * The date when the bank account last got used.
     * @type {string}
     * @memberof BankAccountResponse
     */
    'dateLastUsed'?: string;
    /**
     * The date when the bank account is verified.
     * @type {string}
     * @memberof BankAccountResponse
     */
    'dateVerified'?: string;
    /**
     * The token of the bank account.
     * @type {string}
     * @memberof BankAccountResponse
     */
    'bankToken'?: string;
    /**
     * The type of the bank account, such as CHECKING | SAVINGS.
     * @type {string}
     * @memberof BankAccountResponse
     */
    'accountType'?: string;
    /**
     * The corporate type of the bank account, such as PERSONAL | CORPORATE.
     * @type {string}
     * @memberof BankAccountResponse
     */
    'accountCorporate'?: string;
    /**
     * Verified status of the bank account, 1|0.
     * @type {string}
     * @memberof BankAccountResponse
     */
    'verified'?: string;
    /**
     * Ready status of the bank account, 1|0.
     * @type {string}
     * @memberof BankAccountResponse
     */
    'ready'?: string;
    /**
     * The institution number of Canadian Bank Account that identifies the bank.
     * @type {string}
     * @memberof BankAccountResponse
     */
    'bankIdNumber'?: string;
    /**
     * The transit number of Canadian Bank Account. Shows which branch you opened your account at.
     * @type {string}
     * @memberof BankAccountResponse
     */
    'transitNumber'?: string;
    /**
     * The routing number of US Bank Account. Identifies the financial institution on which it was drawn.
     * @type {string}
     * @memberof BankAccountResponse
     */
    'routingNumber'?: string;
    /**
     * Last 4 digits of the bank account number.
     * @type {string}
     * @memberof BankAccountResponse
     */
    'bankAccountNumberL4'?: string;
    /**
     * 
     * @type {Address}
     * @memberof BankAccountResponse
     */
    'address'?: Address;
}

