/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CardTerminalAddress
 */
export interface CardTerminalAddress {
    /**
     * 
     * @type {string}
     * @memberof CardTerminalAddress
     */
    'street1'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardTerminalAddress
     */
    'street2'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardTerminalAddress
     */
    'city'?: string;
    /**
     * Abbreviation of province
     * @type {string}
     * @memberof CardTerminalAddress
     */
    'province'?: string;
    /**
     * Abbreviation of country
     * @type {string}
     * @memberof CardTerminalAddress
     */
    'country'?: string;
    /**
     * Postal or zip code
     * @type {string}
     * @memberof CardTerminalAddress
     */
    'postalCode'?: string;
}

