/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CardBatch
 */
export interface CardBatch {
    /**
     * Id of Card batch
     * @type {number}
     * @memberof CardBatch
     */
    'id'?: number;
    /**
     * Date Card batch is Created
     * @type {string}
     * @memberof CardBatch
     */
    'dateCreated'?: string;
    /**
     * Date Card batch is last updated
     * @type {string}
     * @memberof CardBatch
     */
    'dateUpdated'?: string;
    /**
     * Date Card Batch is closed
     * @type {string}
     * @memberof CardBatch
     */
    'dateClosed'?: string;
    /**
     * True if the batch is closed. Else false
     * @type {boolean}
     * @memberof CardBatch
     */
    'closed'?: boolean;
    /**
     * Id of associated Terminal
     * @type {number}
     * @memberof CardBatch
     */
    'terminalId'?: number;
    /**
     * Batch Number
     * @type {number}
     * @memberof CardBatch
     */
    'batchNumber'?: number;
    /**
     * Approved sales net refunds and voids
     * @type {number}
     * @memberof CardBatch
     */
    'netSales'?: number;
    /**
     * Gross sales
     * @type {number}
     * @memberof CardBatch
     */
    'totalSales'?: number;
    /**
     * Gross refunds
     * @type {number}
     * @memberof CardBatch
     */
    'totalRefunds'?: number;
    /**
     * Voided amount
     * @type {number}
     * @memberof CardBatch
     */
    'totalReversed'?: number;
    /**
     * Amount of voided refunds
     * @type {number}
     * @memberof CardBatch
     */
    'totalRefundsReversed'?: number;
    /**
     * Total number of transactions
     * @type {number}
     * @memberof CardBatch
     */
    'countTotal'?: number;
    /**
     * Number of approved transactions
     * @type {number}
     * @memberof CardBatch
     */
    'countApproved'?: number;
    /**
     * Number of declined transactions
     * @type {number}
     * @memberof CardBatch
     */
    'countDeclined'?: number;
}

