/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Card1
 */
export interface Card1 {
    /**
     * The card holder name.
     * @type {string}
     * @memberof Card1
     */
    'cardHolderName'?: string;
    /**
     * The F6L4 of card.
     * @type {string}
     * @memberof Card1
     */
    'cardF6L4'?: string;
    /**
     * Card token
     * @type {string}
     * @memberof Card1
     */
    'cardToken'?: string;
}

