/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CardTerminalsRequest
 */
export interface CardTerminalsRequest {
    /**
     * The abbreviation of card terminal\'s currency. Possible values are CAD | USD
     * @type {string}
     * @memberof CardTerminalsRequest
     */
    'currency'?: string;
    /**
     * The card terminal\'s status. possible values are ACTIVE | INACTIVE
     * @type {string}
     * @memberof CardTerminalsRequest
     */
    'status'?: string;
}

