/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CheckoutInitDefaultResponse
 */
export interface CheckoutInitDefaultResponse {
    /**
     * List of errors
     * @type {Array<string>}
     * @memberof CheckoutInitDefaultResponse
     */
    'errors'?: Array<string>;
}

