/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Discount } from './discount';
import { InvoiceBase } from './invoice-base';
import { InvoiceCreate } from './invoice-create';
import { InvoiceCreateAfterProcessing } from './invoice-create-after-processing';
import { LineItem } from './line-item';
import { Pickup } from './pickup';
import { Shipping } from './shipping';
import { Tax } from './tax';

/**
 * @type CreateInvoiceRequest
 * @export
 */
export type CreateInvoiceRequest = InvoiceBase & InvoiceCreate & InvoiceCreateAfterProcessing;


