/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Discount } from './discount';
import { Invoice } from './invoice';
import { InvoiceCreate } from './invoice-create';
import { InvoiceCreateAfterProcessing } from './invoice-create-after-processing';
import { InvoiceResponseBase } from './invoice-response-base';
import { LineItem } from './line-item';
import { Pickup } from './pickup';
import { Shipping } from './shipping';
import { Tax } from './tax';

/**
 * @type CreateInvoice200Response
 * @export
 */
export type CreateInvoice200Response = Invoice & InvoiceCreate & InvoiceCreateAfterProcessing & InvoiceResponseBase;


