/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';

/**
 * 
 * @export
 * @interface CustomerRequest
 */
export interface CustomerRequest {
    /**
     * The unique customer code. If blank, it will be automatically generated.
     * @type {string}
     * @memberof CustomerRequest
     */
    'customerCode'?: string;
    /**
     * The primary contact name (full name) of the customer.
     * @type {string}
     * @memberof CustomerRequest
     */
    'contactName'?: string;
    /**
     * The business name of the customer. There must be either a contact name or business name present.
     * @type {string}
     * @memberof CustomerRequest
     */
    'businessName'?: string;
    /**
     * The cell phone number of the customer.
     * @type {string}
     * @memberof CustomerRequest
     */
    'cellPhone'?: string;
    /**
     * 
     * @type {Address}
     * @memberof CustomerRequest
     */
    'billingAddress'?: Address;
    /**
     * 
     * @type {Address}
     * @memberof CustomerRequest
     */
    'shippingAddress'?: Address;
}

