/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Card1 } from './card1';

/**
 * 
 * @export
 * @interface Customer
 */
export interface Customer {
    /**
     * Id of Customer
     * @type {number}
     * @memberof Customer
     */
    'id'?: number;
    /**
     * Customer code of the customer
     * @type {string}
     * @memberof Customer
     */
    'customerCode'?: string;
    /**
     * Name of the business
     * @type {string}
     * @memberof Customer
     */
    'businessName'?: string;
    /**
     * Contact Name
     * @type {string}
     * @memberof Customer
     */
    'contactName'?: string;
    /**
     * Cell phone number of customer
     * @type {string}
     * @memberof Customer
     */
    'cellPhone'?: string;
    /**
     * 
     * @type {Address}
     * @memberof Customer
     */
    'billingAddress'?: Address;
    /**
     * 
     * @type {Address}
     * @memberof Customer
     */
    'shippingAddress'?: Address;
    /**
     * Array of cards stored in the vault associated with this customer.
     * @type {Array<Card1>}
     * @memberof Customer
     */
    'cards'?: Array<Card1>;
}

