/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Discount
 */
export interface Discount {
    /**
     * Total Discount Amount of the Invoice
     * @type {number}
     * @memberof Discount
     */
    'amount': number;
    /**
     * Discount Details/Code
     * @type {string}
     * @memberof Discount
     */
    'details': string;
}

