/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Invoice } from './invoice';
import { InvoiceResponseBase } from './invoice-response-base';

/**
 * @type GetInvoices200ResponseInner
 * @export
 */
export type GetInvoices200ResponseInner = Invoice & InvoiceResponseBase;


