/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';

/**
 * 
 * @export
 * @interface InvoiceUpdate
 */
export interface InvoiceUpdate {
    /**
     * The currency abbreviation of the invoice, such as CAD or USD. This should match currency of existing invoice.
     * @type {string}
     * @memberof InvoiceUpdate
     */
    'currency'?: string;
    /**
     * The type of the invoice, such as ESTIMATE | INVOICE | QUOTE | ORDER | PURCHASE_ORDER | STATEMENT | REGISTRATION | CREDIT.
     * @type {string}
     * @memberof InvoiceUpdate
     */
    'type'?: string;
    /**
     * The status of invoice, such as DUE | SHIPPED | COMPLETED | CANCELLED
     * @type {string}
     * @memberof InvoiceUpdate
     */
    'status'?: string;
    /**
     * 
     * @type {Address}
     * @memberof InvoiceUpdate
     */
    'billingAddress'?: Address;
}

