/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Discount } from './discount';
import { LineItem } from './line-item';
import { Pickup } from './pickup';
import { Shipping } from './shipping';
import { Tax } from './tax';

/**
 * 
 * @export
 * @interface InvoiceCreateAfterProcessing
 */
export interface InvoiceCreateAfterProcessing {
    /**
     * 
     * @type {Shipping}
     * @memberof InvoiceCreateAfterProcessing
     */
    'shipping'?: Shipping;
    /**
     * 
     * @type {Pickup}
     * @memberof InvoiceCreateAfterProcessing
     */
    'pickup'?: Pickup;
    /**
     * 
     * @type {Tax}
     * @memberof InvoiceCreateAfterProcessing
     */
    'tax'?: Tax;
    /**
     * 
     * @type {Discount}
     * @memberof InvoiceCreateAfterProcessing
     */
    'discount'?: Discount;
    /**
     * 
     * @type {Array<LineItem>}
     * @memberof InvoiceCreateAfterProcessing
     */
    'lineItems'?: Array<LineItem>;
}

