/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LineItem
 */
export interface LineItem {
    /**
     * 
     * @type {string}
     * @memberof LineItem
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof LineItem
     */
    'sku'?: string;
    /**
     * The quantity of the line item. Can have upto 2 decimal places
     * @type {number}
     * @memberof LineItem
     */
    'quantity': number;
    /**
     * 
     * @type {number}
     * @memberof LineItem
     */
    'price': number;
    /**
     * Total = Price * Quantity
     * @type {number}
     * @memberof LineItem
     */
    'total': number;
    /**
     * This will be added to Invoice\'s total tax amount
     * @type {number}
     * @memberof LineItem
     */
    'taxAmount'?: number;
    /**
     * This will be added to Invoice\'s total discount amount
     * @type {number}
     * @memberof LineItem
     */
    'discountAmount'?: number;
}

