/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Discount } from './discount';
import { InvoiceBase } from './invoice-base';
import { InvoiceCreateAfterProcessing } from './invoice-create-after-processing';
import { LineItem } from './line-item';
import { Pickup } from './pickup';
import { Shipping } from './shipping';
import { Tax } from './tax';

/**
 * @type PaymentRequestInvoice
 * To be filled when creating new invoice to be associated to transaction. Will be linked to Customer owning the Card used
 * @export
 */
export type PaymentRequestInvoice = InvoiceBase & InvoiceCreateAfterProcessing;


