/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Pickup
 */
export interface Pickup {
    /**
     * Pickup Date
     * @type {string}
     * @memberof Pickup
     */
    'date': string;
    /**
     * Name of the person to pickup
     * @type {string}
     * @memberof Pickup
     */
    'name'?: string;
}

