/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { CardData } from './card-data';
import { CardDataCardData } from './card-data-card-data';
import { PaymentRequest } from './payment-request';
import { PaymentRequestInvoice } from './payment-request-invoice';

/**
 * @type PurchaseRequest
 * @export
 */
export type PurchaseRequest = CardData & PaymentRequest;


