/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RefundRequest
 */
export interface RefundRequest {
    /**
     * The transaction ID of the purchase/capture transaction.
     * @type {number}
     * @memberof RefundRequest
     */
    'originalTransactionId': number;
    /**
     * The amount to refund. Must be less or equal to the original purchase/capture amount.
     * @type {number}
     * @memberof RefundRequest
     */
    'amount': number;
    /**
     * IP address of the customer making the transaction, used as part of fraud detection.
     * @type {string}
     * @memberof RefundRequest
     */
    'ipAddress': string;
    /**
     * Set to indicate that the transaction is e-commerce. When set, the Helcim Fraud Defender will provide further analysis.
     * @type {boolean}
     * @memberof RefundRequest
     */
    'ecommerce'?: boolean;
}

