/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';

/**
 * 
 * @export
 * @interface Shipping
 */
export interface Shipping {
    /**
     * Total Shipping Amount of the Invoice
     * @type {number}
     * @memberof Shipping
     */
    'amount': number;
    /**
     * This will show up in the invoice
     * @type {string}
     * @memberof Shipping
     */
    'details': string;
    /**
     * 
     * @type {Address}
     * @memberof Shipping
     */
    'address': Address;
}

