/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SuccessfulAchTransactionResponse
 */
export interface SuccessfulAchTransactionResponse {
    /**
     * The transaction id
     * @type {number}
     * @memberof SuccessfulAchTransactionResponse
     */
    'transactionId'?: number;
    /**
     * The id of associated card batch
     * @type {number}
     * @memberof SuccessfulAchTransactionResponse
     */
    'batchId'?: number;
    /**
     * The date(Mountain Time) when the transaction is created.
     * @type {string}
     * @memberof SuccessfulAchTransactionResponse
     */
    'dateCreated'?: string;
    /**
     * The status of the transaction. possible values are APPROVED | DECLINED | IN_PROGRESS | CANCELLED | PENDING
     * @type {string}
     * @memberof SuccessfulAchTransactionResponse
     */
    'statusAuth'?: string;
    /**
     * The status of the transaction. possible values are OPENED | CLEARED | REJECTED | CONTESTED | RETURNED
     * @type {string}
     * @memberof SuccessfulAchTransactionResponse
     */
    'statusClearing'?: string;
    /**
     * The type of the transaction. possible values are WITHDRAWAL | DEPOSIT | SETTLE | REVERSE | REFUND
     * @type {string}
     * @memberof SuccessfulAchTransactionResponse
     */
    'type'?: string;
    /**
     * The amount of processed transaction
     * @type {number}
     * @memberof SuccessfulAchTransactionResponse
     */
    'amount'?: number;
    /**
     * The abbreviation of the transaction\'s currency
     * @type {string}
     * @memberof SuccessfulAchTransactionResponse
     */
    'currency'?: string;
    /**
     * Approval Code
     * @type {string}
     * @memberof SuccessfulAchTransactionResponse
     */
    'approvalCode'?: string;
    /**
     * Bank account number
     * @type {string}
     * @memberof SuccessfulAchTransactionResponse
     */
    'bankAccountNumber'?: string;
    /**
     * Bank Token associated with bankAccount
     * @type {string}
     * @memberof SuccessfulAchTransactionResponse
     */
    'bankToken'?: string;
    /**
     * Invoice number associated to the transaction
     * @type {string}
     * @memberof SuccessfulAchTransactionResponse
     */
    'invoiceNumber'?: string;
}

