/*
The Helcim API

This API covers publicly accessible merchant actions

The version of the OpenAPI document: 2.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { InvoiceBase } from './invoice-base';
import { InvoiceUpdate } from './invoice-update';

/**
 * @type UpdateInvoiceRequest
 * @export
 */
export type UpdateInvoiceRequest = InvoiceBase & InvoiceUpdate;


